### PR TITLE
zdharma >> zdharma-continuum

### PR DESCRIPTION
**Pull request by ss-o**
But I rather use [z-shell/zinit](https://github.com/z-shell/zinit) :+1:  :100:  :upside_down_face:

### CODE REVIEW

**Comment by black7375** [comment]
Is there any difference between `zdharma-continum` and `z-shell`?
Is it just another repo with only admins?

**Comment by ss-o** [comment]
zdharma-continuum is more community-supported (currently), but based on their commits, I am unsure of its future, but don't have anything against it. The previous owner (psprint) made huge efforts to maintain a project. Seems like the community has mostly been users rather than supporters of the project. (My personal opinion)

I started z-shell/zinit around the same time as zdharma-continuum, but hasn't advertised, because many issues had to be fixed, while zdharma-continuum advertised it without actual changes made to the project. This is the reason why z-shell lost popularity across the community. However, because of huge efforts done to project in a short time, I plan an alternative with smaller, but more targeted community + plus split approach to the project user-based as follows:
  - **General Users:** provides simpler installation and documentation and overall suggestions template-based which allows users to choose from pre-configured options.
  - **Developers:** provides full flexibility and separate detailed documentation.
  Mentioned above approach should allow a wider range to use the project, increase productivity, and easier way to achieve goals as the current state of zinit seems to be complex for regular users and only users who are more familiar with zinit code structure can take full advantage of it. 

  Z-Shell is supported by a small group of cybersecurity entusiats (This adds some security value). I am long term Linux systems administrator familiar with zinit project code, as well as online privacy and overall security enthusiast (Barely sociable for the mentioned reasons :upside_down_face: ). Recently I reviewed previous contributors to zinit and their online activity. Also used BlaCk-Void-Zsh in the past. Based on mentioned above I could add you as a z-shell/zinit maintainer for decision-making on its future if there is any interest.

Based on overall past information and current state both projects has advantages and disadvantages in my opinion. I really respect psprint (a.k.a zdharma) work and looking forward to its continuation.

Regards,

**Comment by black7375** [comment]
Thank you for your kind explanation.
I wonder what will happen next.

**Comment by ss-o** [comment]
You are than welcome. For future references my mail is: admin@digitalclouds.dev

**Comment by pschmitt** [comment]
Hi @ss-o

[zdharma-continuum](https://github.com/zdharma-continuum) member here.
I have to say that I ready do not appreciate the FUD spreading here, on an unrelated repo.

Most of what you wrote is simply put false. A few notes:

- We do have plans for the future of [zdharma-continuum/zinit](https://github.com/zdharma-continuum/zinit) - see our [4.0 milestone](https://github.com/zdharma-continuum/zinit/milestone/1) for example
- What commits make you wonder about our future?!
- I'd expect security enthusiasts to sign their commits...
- [You very much advertised z-shell on reddit](https://www.reddit.com/r/zinit/comments/qmps83/zinit_rework//) and that's probably why your project hasn't exactly taken off given the kind of nonsense you wrote on there regarding the governance model.

Anyway please get in touch with me directly.
Sorry to bother you with this crap, black7375!

**Pull request merged**
